
spring:
  application:
    name: ERP_SpringBoot-Experiment
  profiles:
    active: dev

  contact:
    name: ANNOEYE
    url: zalo.me/0971791373
    email: annoeye@gmail.com

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: Spring_app
    password: ddinhnn11
    driver-class-name: oracle.jdbc.OracleDriver

  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: erpspringbootexperiment@gmail.com
    password: "onfw cbkp xfmh arow"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      static-locations: classpath:/static/

  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: ALWAYS

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

integration:
  minio:
    access-key: admin
    secret-key: admin@2025
    url: http://localhost:9000

server:
  port: 8080
  url: http://localhost:8080

frontend:
  url: http://localhost:5173/berry-vue

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false
#  default-consumes-media-type: multipart/form-data
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: N0pwM0VjcmV0S2V5Rm9ySlBUSXNzdWVyQW5kVmVyaWZpY2F0aW9uUHVycG9zZXM=

logging:
  level:
    root: INFO
    com:
      anno:
        ERP_SpringBoot_Experiment:
          service: DEBUG
    org:
      apache:
        kafka:
          clients:
            admin.AdminClientConfig: WARN
            consumer.ConsumerConfig: WARN
            producer.ProducerConfig: WARN
      hibernate:
        apache:
          catalina:
            loader:
              WebappClassLoaderBase: ERROR
        tool:
          schema:
            internal:
              ExceptionHandlerLoggedImpl: ERROR
        springframework:
          data:
            repository:
              config:
                RepositoryConfigurationExtensionSupport: ERROR
    org.hibernate: WARN
#    org.springframework: DEBUG


  pattern:
    console: "%boldYellow(%d{HH:mm:ss.SSS}) %boldCyan(%d{yyyy-MM-dd}) %green([%thread]) %highlight(%-5level) %cyan(%logger{36}) %magenta([%file:%line]) %yellow(-) %msg%n"

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:4200/payments/payment-callback}" # return
  tmn-code: "SYXILNQA"
  secret-key: "PR6MH2S24AM1566BB0HKV9C4UAQ3BNVH"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"